import type { Metadata } from 'next';
import './globals.css';
import TanStackProvider from './components/TanStackProvider/TanStackProvider';
import Header from './components/Header/Header';
import './globals.css';

export const metadata: Metadata = {
  title: 'AI ManagerDB',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          <TanStackProvider>{children}</TanStackProvider>
        </main>
      </body>
    </html>
  );
}
